services:
  # Web application container
  app:
    container_name: epicollect5-server
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "${WEB_PORT:-80}:80"  # Uses WEB_PORT env var or defaults to 80
    volumes:
      - ./:/var/www/docker
      - html_prod:/var/www/html_prod
    environment:
      UPDATE_CODEBASE: "${UPDATE_CODEBASE}"
      TERM: xterm
    healthcheck:
      test: ["CMD", "test", "!", "-f", "/tmp/deployment_in_progress"]
      interval: 10s
      timeout: 5s
      retries: 120  # Allow up to 20 minutes for deployment
      start_period: 60s
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - epicollect_network

  # Database container
  db:
    container_name: epicollect5-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    restart: unless-stopped
    networks:
      - epicollect_network
networks:
  epicollect_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  letsencrypt:  # Volume for Let's Encrypt certificates
    driver: local
  html_prod:
      driver: local

